### ISSUE TITLE
Improve short path names

### ISSUE THREAD

**Issue by silenc3r** [Alok/notational-fzf-vim#12]
- [x] Replacing ```/home/user``` with ~ would be nice.
 - [ ] When there's only one note folder display file names only.
 - [x] When there are multiple folders strip common parent folder for all note folders and replace it with ```../``` eg. if my note folders look like this:

    /home/user/Documents/Notes/private
    /home/user/Documents/Notes/work
    /home/user/Documents/Notes/wiki

display them as:

    ../private
    ../work
    ../wiki

**Comment by Alok** [comment]
1. Probably
2. Maybe but less likely
3. Maybe as another configurable option.

I'm busy these days, so don't hold your breath.

**Comment by Alok** [comment]
\#1 is in the latest commit.

**Comment by Alok** [comment]
Not going to do 2 since I don't want to add special cases to the code. If you can think of a clean way to do it, as much as I hate this phrase, feel free to send a pull request.
