### ISSUE TITLE
Can't find g:nv_search_paths even though it is set

### ISSUE THREAD

**Issue by softinio** [Alok/notational-fzf-vim#17]
# Summary of Problem

I get this error: 

```
Error detected while processing /Users/salar.rahmanian/.vim/plugged/notational-fzf-vim/plugin/notational_fzf.vim:
line   18:
`g:nv_search_paths` is not defined.
```

my config: 

```
"notational-fzf-vim
let g:nv_main_directory=['~/notes']
let g:nv_search_paths=['~/notes']
let g:nv_default_extension='.md'
let g:nv_create_note_key='ctrl-x'
let g:nv_keymap={
                  \ 'ctrl-s': 'split ',
                  \ 'ctrl-v': 'vertical split ',
                  \ 'ctrl-t': 'tabedit ',
                  \ })
let g:nv_create_note_window='vertical split'
```

Any ideas?

**Comment by softinio** [comment]
found what the issue was closing. My env issue.

**Comment by diego898** [comment]
@softinio I am seeing the same problem - can you clarify what it was?

**Comment by nocibambi** [comment]
> @softinio I am seeing the same problem - can you clarify what it was?

I had the same problem. I found the solution (for my case) in the [install guide](https://github.com/alok/notational-fzf-vim#required-settings). Basically, I had add that line to `.vimrc`.

> Required Settings
> 
> You have to define a list of directories or files (which all must be strings) to search. This setting is named `g:nv_search_paths`.
> 
> Remember that these can be relative links.
> 
> ```vim
> " example
> let g:nv_search_paths = ['~/wiki', '~/writing', '~/code', 'docs.md' , './notes.md']
> ```
