### ISSUE TITLE
Feature request: change height 

### ISSUE THREAD

**Issue by bookcasey** [alok/notational-fzf-vim#23]
It seems like the height of the entire interface is always around 40% of the window. Would it be possible to add the ability to change the height like in [fzf](https://github.com/junegunn/fzf#layout)? It would be great to use this in fullscreen mode.

**Comment by alok** [comment]
I'm not going to implement this, but will accept a PR.

**Comment by bookcasey** [comment]
I'd be happy to submit a PR, but I'm struggling to understand how the height is currently controlled. I've tried playing with the `--height` flag with no success. Can you point me in the right direction?

**Comment by alok** [comment]
Implemented in latest commit.
