### ISSUE TITLE
Screencast is impossible to understand on anything but the largest monitor

### ISSUE THREAD

**Issue by lewisthompson** [alok/notational-fzf-vim#26]
Even on a 15" MBP (a pretty common device, I expect) it's very difficult to read follow the screencast.

A much lower resolution screencast would be greatly appreciated.

**Comment by alok** [comment]
This is what I get for recording it on a 40" monitor. I'll redo it.

**Comment by lewisthompson** [comment]
Thanks!  I wasn't expecting such a fast response!  I feel cheeky now but you did say any and all feedback was appreciated!

**Comment by alok** [comment]
Done
