### ISSUE TITLE
Project should have a license

### ISSUE THREAD

**Issue by Ealhad** [alok/notational-fzf-vim#32]
This project does not seem to have a license right now. It would be good if you could add one so users get clarity. 

You can take a look at https://choosealicense.com/ if you want a quick overview of the main licenses.

**Comment by azah** [comment]
Just to clarify, the reason for this is that this code is still copyrighted unless you add a license. It's not open-source, it's source-available (since no one can contribute, only you have that right).

I second the usage of https://choosealicense.com/, it's also made by github.

**Comment by pinusc** [comment]
I would say it's open source but not free. As an alternative for the MIT license, I recommend the GPL license, also hugely popular and more in support of free software

**Comment by azah** [comment]
@pinusc In order for something to be Open Source, it must meet the following definition: https://en.wikipedia.org/wiki/The_Open_Source_Definition. 

You can see all approved licenses here that meet this definition:
https://opensource.org/licenses/alphabetical
This includes the GNU GPLv2/3 License, MIT License, and many others.

A project on github without a license is *not* `open source`, nor `free`. It is still **fully copyrighted**, barring anyone from freely modifying it. Hence, `source-available`. See [github's documentation](https://help.github.com/en/articles/licensing-a-repository):

> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and **no one may reproduce, distribute, or create derivative works from your work**. [emphasis mine]

This gets murky with the concept of a 'fork', but that's not in the scope of this discussion.

**Comment by alok** [comment]
Apache 2
