### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by sobfiggis** [alok/notational-fzf-vim#34]
Per the README:
>plugin may not work on Windows. I only have a Mac to test it on. It works for sure on Mac with Neovim, and should work in terminal Vim, since it's just a wrapper over fzf.

Hoping this will be helpful in getting NV working on Windows.

rg/fzf versions are current:
![image](https://user-images.githubusercontent.com/5481042/58661856-7d729780-82ee-11e9-9196-6164abdbc0dc.png)

And fzf is working in vim:
![image](https://user-images.githubusercontent.com/5481042/58667412-87e75e00-82fb-11e9-9e33-ea08e7fc4d48.png)

Once :NV is opened it quickly gives an error:
`The system cannot find the path specified.`
![image](https://user-images.githubusercontent.com/5481042/58666585-5b324700-82f9-11e9-8599-cc75e8b78be6.png)

And then gives a blank nv split:
![image](https://user-images.githubusercontent.com/5481042/58666630-7dc46000-82f9-11e9-8b7f-291080a5d1bd.png)

I have tried using both relative and absolute paths. And I have tried windows and nix paths. ("~/folder", "C:\\\Users\\\\$USER\\\folder", etc)

Let me know if there is any other information that would be helpful with this.

**Comment by alok** [comment]
I don't use Windows and adding support for it is work I don't have time for these days. I'm afraid I'll have to fob you off with "send a PR".

**Comment by sobfiggis** [comment]
Leaving an issue open is asking for a PR

**Comment by DominoTree** [comment]
Would also love this - if I get some time I'll see if I can get it working myself and make a PR.

**Comment by sobfiggis** [comment]
Had some free time and dug into this a bit more. I'm convinced it's just an issue with paths.

/dev/null being the easy fix. 

![image](https://user-images.githubusercontent.com/5481042/59151235-42125000-89f5-11e9-9ab0-03702ee508c4.png)
vs
![image](https://user-images.githubusercontent.com/5481042/59151239-49395e00-89f5-11e9-8781-e98f9c568b72.png)

But there are definitely some more issues (for windows) with the paths being fed to fzf.

Will poke at it some more another day.

**Comment by alok** [comment]
Try it with short pathnames turned off. The python script has a few hardcoded forward slashes, and may be splitting incorrectly on the colon in the c drive name.

**Comment by alok** [comment]
@DominoTree @sobfiggis Try the master branch and let me know if it's fixed.
