### ISSUE TITLE
add directory to exclude

### ISSUE THREAD

**Issue by intrepidlemon** [alok/notational-fzf-vim#37]
# Summary of Problem

There should be a way to add a directory to exclude from the search results. 

usecase: I get a lot of results from my `.git` directory. There should be a way to either exclude all hidden directories from search by default unless explicitly specified, or let me specify that my .git directory should not be included in the search results.

**Comment by alok** [comment]
Read the readme

let g:nv_ignore_pattern = ['summarize-*', 'misc*']
