### ISSUE TITLE
Zsh Prompt

### ISSUE THREAD

**Issue by alexozer** [alok/notational-fzf-vim#38]
Sorry for the unrelated noise, but which zsh prompt and terminal colors are you using? I like the look.

I also like the look of this plugin as well and will probably be using it shortly :)

**Comment by alok** [comment]
https://github.com/sindresorhus/pure, solarized dark

--- Alok

**Comment by alexozer** [comment]
Interesting, I constantly see instances of that zsh prompt but never seem to associate it back to Pure.
