### ISSUE TITLE
Blank search box

### ISSUE THREAD

**Issue by johngodlee** [alok/notational-fzf-vim#39]
I have installed notational-fzf-vim using Vundle and set the appropriate `nv_search_paths` in my .vimrc:

```
Plugin 'Alok/notational-fzf-vim' 

let g:nv_search_paths = ['/Users/user/Downloads/notes']
```

**When I call the plugin in vim with `:NV`, while the fzf search and preview window appear, they are both empty and no files are found by fzf, displaying `0/0` in the search line.** 

A new file can be created with ctrl-x, and it successfully uses the path provided by `nv_search_paths`.

`/Users/user/Downloads/notes` contains two non-empty `.md` files called `test.md` and `test2.md`.

`fzf` and `rg` work in the shell with no issues.

Python 3.7.3 is installed. `which python` returns: `/usr/local/opt/python/libexec/bin/python`, which is included in my `$PATH`.

Running macOS Mojave 10.14.5.

Vim 8.1 compiled by Homebrew.

**Comment by alok** [comment]
What are the contents of the test files? If they only contain whitespace, then they will be skipped since this searches for non blank lines.

**Comment by johngodlee** [comment]
test.md:

```
This should be the first file which contains 1 note

This is a note
```

test2.md:

```
This is the second note, which should contain 2 notes

Nightline is note 

Second street is note
```

**Comment by alok** [comment]
Huh. This one looks like it'll take some thinking to figure out. It'd be nice if you could try it out on neovim with similar settings just to cross-reference (I only use nvim), but isn't necessary.

**Comment by alok** [comment]
What's the version of `rg` and `fzf` too?

**Comment by johngodlee** [comment]
I'll have a look with `nvim` tomorrow. Thanks for your help so far.

`fzf --version`: 0.18.0 (brew)

`rg --version`: ripgrep 11.0.1 -SIMD -AVX (compiled) +SIMD +AVX (runtime)

**Comment by johngodlee** [comment]
I tried with `nvim` and the same problem occurs. This is the exact process I went through:

`brew install neovim`

Created an `init.vim` in `~/.config/nvim/`:

```
filetype off

set rtp+=~/.config/nvim/bundle/Vundle.vim
call vundle#begin('~/.config/nvim/bundle')

Plugin 'VundleVim/Vundle.vim'
Plugin 'junegunn/fzf'
Plugin 'junegunn/fzf.vim'
Plugin 'Alok/notational-fzf-vim'

call vundle#end()

let g:nv_search_paths = ['/Users/johngodlee/Desktop/test']
```

Installed Vundle with:

```
mkdir -p ~/.config/nvim/bundle
git clone https://github.com/VundleVim/Vundle.vim.git ~/.config/nvim/bundle/Vundle.vim
```

Opened `nvim` and installed Plugins with `PluginInstall`.

Called `notational-fzf-vim` with `:NV`.

Again, the window appears with the preview and fzf input, but no files are recognised in the fzf list. The plugin is successfully reading `nv_search_paths` as new files can be created and files present within `/Users/johngodlee/Desktop/test` can be opened using the plugin by typing their `$BASENAME` and hiting <Ctrl>-x e.g. `tester` for file `/Users/johngodlee/Desktop/test/tester.md`

**Comment by alok** [comment]
Do you have a .ignore file that rg may be respecting? Try adding `\ '-uuu',` after the line with `--follow` on it and let me know.

**Comment by johngodlee** [comment]
That worked!

My dotfiles are managed with a git repo in `~/`, with a gitignore file which ignores everything unless I add it with `git add -f`. I guess `rg` was respecting this gitignore and ignoring everything under `~/`. Checked by moving my test directory above `~/` on the original config and sure enough it worked fine. Thanks.

I'll submit a pull request with this as a boolean option

**Comment by alok** [comment]
Well, that's a horrifying setup. Thanks for the PR.

**Comment by alok** [comment]
Certainly the most interesting approach to dotfile management I've seen so far.

**Comment by nocibambi** [comment]
I had the very same issue. However, the solution proposed above (only) did not help.

It turned out that I did not have `libpcre2-8-0` installed which `rg` required. (I find this out only when run `rg --help` to see how can I check its ignore policy.) I find this strange as I would think that this should come with install as a dependency.

After installing the library with `sudo apt-get install libpcre2-8-0`, however, it worked nicely.
