### ISSUE TITLE
Fuzzy search word order not respected

### ISSUE THREAD

**Issue by daturkel** [alok/notational-fzf-vim#42]
# Summary of Problem

From the docs:
> It does not search in a fully fuzzy fashion because that's less useful for prose. It looks for full words, but they don't have to be next to each other, **just in the right order.**

I noticed this feature doesn't seem to be working? As an example, I created a file with the text "word another hello" and then search for "another hello word" (i.e. backwards) and it still comes up.

<img width="1069" alt="Screenshot 2019-06-10 10 28 15" src="https://user-images.githubusercontent.com/1828387/59202482-912dc180-8b6a-11e9-8916-e26226f6a38d.png">

I happen to actually _like_ this functionality since it means I can add a list of tags to the top of my file and don't have to remember the order of the tags, so maybe there should be an option to either force respecting search term order, or else ignore order?

edit: also thank you for making this amazing tool :) i'm a huge vim and fzf fan, and used to be a big nvalt use too, so this is a great solution for me

**Comment by alok** [comment]
That's just me writing an incorrect readme. Afk, so mind sending a PR that
deletes that bit?
-- 
-- Alok
