### ISSUE TITLE
Problems when rg enters the .git folder

### ISSUE THREAD

**Issue by danielwe** [alok/notational-fzf-vim#46]
The plugin passes the `--hidden` flag to rg, which means that when used in a git repo it will enter the .git folder. This folder often contains binary files that cannot be identified as such (i.e., that don't contain NUL bytes), and are therefore searched by rg. Besides giving fzf much more work than necessary, this sometimes breaks the search completely and prevents fzf from finding any matches at all (perhaps due to the control characters emitted when rendering the binary files as text; when I execute the offending search in the terminal it screws up the colors).

I can think of the following possible solutions:

* Add flags for rg to explicitly skip vcs folders, i.e., `--glob '!.git' --glob '!.hg' --glob '!.svn'`;
* Remove the `--hidden` flag altogether (or make it configurable, preferably off by default). Do people actually store their notes in hidden files and folders?

As for reproducibility, this turns out to be difficult (it only breaks in one of my repos, which happens to be the one where I need this plugin the most), but try something like `:NV #\S` with a git repo in `g:nv_search_paths`.

**Comment by alok** [comment]
What is `let g:nv_use_ignore_files = 1` set to?

**Comment by danielwe** [comment]
Not set, i.e., enabled as per the default. But it's not really relevant; the `--hidden` and `--no-ignore` flags are orthogonal, as explained here: <https://github.com/BurntSushi/ripgrep/issues/1303#issuecomment-502642949>. Unless you put `.git` in `.gitignore` (which would be rather unconventional), `--hidden` implies searching .git simply because it's hidden.

**Comment by alok** [comment]
Turns out I have `.git` in my `~/.ignore`. I recommend doing that or trying out `g:nv_ignore_pattern` (see README). I'm trying to rewrite this to support only showing matching files among other things, so I'm not going to put energy into much else right now.

**Comment by danielwe** [comment]
I can do a PR no prob, just let me know which option you prefer: explicit ignore pattern for vcs folders, removing `--hidden`, or making `--hidden` configurable and if so with what default?

**Comment by alok** [comment]
Make hidden configurable, and disable seeing hidden by default.
