### ISSUE TITLE
hangs vim with large files, filling up disks

### ISSUE THREAD

**Issue by Grazfather** [alok/notational-fzf-vim#50]
Now, when I filter I can see the files filter as expected. When I hit 'enter' to open the file under the cursor, the bottom split clears but doesn't close and the file doesn't open, and I have to `kill -9` on vim.

I have a ~14GB dictionary file it may have been searching (I've moved it to obviate the issue). Interestingly the issue only happens after I try to open _another_ file.

It seems to quickly fill up my disk (swap files? I don't know).

It's an avoidable issue by keeping huge files out of the config path, but at the same time it probably shouldn't be writing to disk.

Happy to help root cause.

**Comment by alok** [comment]
I think that's a swap file issue. Just exclude the dictionary.
