### ISSUE TITLE
Feature Request: Changing main directory at runtime

### ISSUE THREAD

**Issue by Laptop765** [alok/notational-fzf-vim#54]
# Summary of Problem

I have multiple Wiki folders and I'd like to change which one `<C-x>` saves to.  I created a quick command for this on my local machine and wanted to [offer it to others](https://github.com/Laptop765/notational-fzf-vim/commit/e341ce3214acd729088e2adb87d55e75a544b9eb).  I didn't want to create a PR to add functionality out of nowhere and figured I'd leave it up to you whether it should be merged to the main plugin.

**Comment by alok** [comment]
See README for `NV_note_handler`. This sounds related. Not gonna merge.

**Comment by Laptop765** [comment]
Makes sense - thanks for considering!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
