### ISSUE TITLE
:read note into current file

### ISSUE THREAD

**Issue by rpietro** [alok/notational-fzf-vim#55]
The software works great, but I am trying to figure a way to :read the note directly into my current file instead of having to open it, copy all, and then insert it.

Thoughts? Thanks

**Comment by alok** [comment]
Sounds like `NV_note_handler` would do that. See `README.md`.

**Comment by rpietro** [comment]
@alok I have been trying to find other scripts using NV_note_handler just to get some ideas, but no success so far. Any hints?  thanks

**Comment by alok** [comment]
See the function `s:handler` in `plugin/notational_fzf.vim`.
