### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by junegunn** [Alok/notational-fzf-vim#6]
Hi,

https://github.com/Alok/notational-fzf-vim#dependencies lists fzf.vim, but I believe your plugin only needs the main fzf repo.

One more thing, you might also want to take a look at "highlight" besides coderay.

https://github.com/junegunn/fzf.vim/blob/master/bin/preview.rb#L7

**Comment by junegunn** [comment]
Closing since this is just a suggestion.

**Comment by Alok** [comment]
That was a handy suggestion. Thanks. I ended up doing both.
