### ISSUE TITLE
No notes appear even though folder exists

### ISSUE THREAD

**Issue by teto** [alok/notational-fzf-vim#62]
## Summary of Problem
After running, I see no notes when python3 is not in PATH but no error is printed whatsover. With python3 in PATH it works fine. Ideally I would like it to use g:python3_host_prog when available (might be neovim specific).

I would like to have some hints about why it didn't work, for instance provide a checkhealth script (for neovim, see `:h health-dev`.

**Comment by alok** [comment]
Python 3 is listed as a dependency, and I'm busy with other stuff next currently, so I won't be implementing it. I will take a PR.
