### ISSUE TITLE
Option to disable reecursive search

### ISSUE THREAD

**Issue by andreasmhallberg** [alok/notational-fzf-vim#65]
## Checklist

- [x ] I updated.

- [ ] `NV_note_handler` cannot fix my issue.

## Summary of Problem

Not sure if `NV_note_handler` can do this, or how.

Is it possible to ad an option to disable recursive searches, so that notational-fzf only looks at files directly in the directories listed in `g:nv_search_paths`?

**Comment by alok** [comment]
No.

**Comment by alok** [comment]
If you want to fork it, you can probably use `rg`'s `--max-depth`flag to implement this.

**Comment by andreasmhallberg** [comment]
That did. Thanks.
