### ISSUE TITLE
E117: Unknown function: fzf#wrap, E116: Invalid arguments for function fzf#run

### ISSUE THREAD

**Issue by williamsmj** [Alok/notational-fzf-vim#7]
When I do `:NV` and hit return in vim I get the errors

```
E117: Unknown function: fzf#wrap
E116: Invalid arguments for function fzf#run
```

I'm not 100% certain I'm using the plugin as intended, as I found the README a little opaque ("Just type in keywords and it will search for them"? Where?) Am I simply using the plugin wrongly? Or is this a real error?

As far as I can tell, I've installed and satisfied the dependencies and configured correctly:
```
$ ls ~/.vim/plugged/notational-fzf-vim/
CHANGELOG.md  README.md  plugin/  screenshots/  shorten_path_for_notational_fzf.py*
$ fzf --version
0.16.5
$ ag --version
ag version 1.0.2
Features:
  +jit +lzma +zlib
$ tail -1 ~/.vimrc
let g:nv_directories = ['~/Dropbox/notes']
```

**Comment by williamsmj** [comment]
Solved my own problem: You need to install the `fzf` vim plugin in addition to `fzf` itself. Might be worth adding that to the README.

**Comment by Alok** [comment]
That *was* in the README. I removed it when @junegunn said it looked unnecessary.

I've updated the README a bit. Please let me know if it's more readable. If not, any criticism is eagerly desired.

**Comment by junegunn** [comment]
No, you don't need `fzf.vim`. You only need vim plugin from the main fzf repo which defines both functions.

**Comment by Alok** [comment]
Fixed in README.
