### ISSUE TITLE
Sort results by recent file access 

### ISSUE THREAD

**Issue by eater** [alok/notational-fzf-vim#72]
## Checklist

- [X ] I updated.

- [X ] `NV_note_handler` cannot fix my issue.

## Summary of Problem

It would be very convenient if the most recently accessed files were sorted first in the search resuls. Is that hard to do? I'm not sure what the current sort is based on.

**Comment by alok** [comment]
It's based on however ripgrep prints them, which is a parallel and therefore unordered process.
