### ISSUE TITLE
Sanitize/adjust file name on create_note_key

### ISSUE THREAD

**Issue by sotte** [alok/notational-fzf-vim#75]
## Checklist

- [x] I updated.
- [ ] `NV_note_handler` cannot fix my issue.

## Summary of Feature

It would be great to make file name creation from search query configurable.
Current state:
```
:NV
Enter query: this is my query
--> ~/notes/this is my query.md
```

Goal state (example):
```
:NV
Enter query: this is my query
--> ~/notes/2020-10_this_is_my_query.md
```

Currently the final file name is build like this:
```
   " Handle creating note.
   if keypress ==? s:create_note_key
     let candidates = [fnameescape(s:main_dir  . '/' . query . s:ext)]
```

I'm proposing to have a `query_to_filename` function that can be overwritten by the user.

(This feature can be implemented by overwriting and adjusting the NV_note_handler. With the proposed solution it would be easier.)

**Comment by alok** [comment]
Not going to implement. You'll have to write a handler. Feel free to post it here if you think others will like it.

**Comment by sotte** [comment]
Fair enough. Thanks for being upfront about it!

This is taken from my private fork of the project. It replaces " " with "_".
```
function! s:handler(lines) abort
   " ...
   " Handle creating note.
   if keypress ==? s:create_note_key
     let clean_query = substitute(query, " ", "_", "g")
     let candidates = [fnameescape(s:main_dir  . '/' . clean_query . s:ext)]
```
