### ISSUE TITLE
Support "window" position

### ISSUE THREAD

**Issue by daturkel** [alok/notational-fzf-vim#78]
## Checklist

- [x] I updated.

- [X] `NV_note_handler` cannot fix my issue.

## Summary of Problem

The default FZF behavior is [now](https://github.com/junegunn/fzf/commit/c60ed1758315f0d993fbcbf04459944c87e19a48) to open FZF in a floating window. However, notational-fzf currently only supports down/left/right/up. Setting `let g:nv_window_direction = "window"` gives me:

```
E721: Duplicate key in Dictionary: "window"
E116: Invalid arguments for function fzf#wrap
E116: Invalid arguments for function fzf#run
```
when I try to run NV.

Is it possible to support the new `window` direction?

edit: I was able to "hack" the setting with this:
```
let g:nv_window_direction = 'fzf_layout'
let g:nv_window_width = { 'window' : { 'width': 0.5, 'height': 0.6, 'highlight': 'Normal' } }
```
which is just a sneaky way of setting the layout by abusing the current options. However, it didn't work correctly. In fact, it seems to give me the same results as `NV!` (fullscreen) rather than a proper floating window.

"hacked" notational-fzf:
<img width="721" alt="Screen Shot 2020-12-17 at 7 07 17 PM" src="https://user-images.githubusercontent.com/1828387/102558314-30eed880-409b-11eb-8fb5-08d9107e8d86.png">

normal fzf:
<img width="718" alt="Screen Shot 2020-12-17 at 7 07 30 PM" src="https://user-images.githubusercontent.com/1828387/102558328-364c2300-409b-11eb-9d0e-1d2fbd2364f5.png">

**Comment by bugbounce** [comment]
@daturkel  This should work for you.
`let g:nv_window_command = {'width': 0.9, 'height': 0.7}`
