### ISSUE TITLE
[suggestion] An option to set a alternative separator when saving new notes

### ISSUE THREAD

**Issue by boojum** [alok/notational-fzf-vim#80]
Hey! First and foremost: thanks for this amazing plugin!

Would it be possible to set a different separator for filename segments when saving a new note? For example, if I type `this is an example note`, it will be saved exactly like that - with withspace separating words in the filename. Would it be possible to set different separator, like `-` or `_`? The filename then would end up being `this-is-an-example-note` or `this_is_an_example_note`.

**Comment by alok** [comment]
Note handler should be able to do this.
