### ISSUE TITLE
Proposal to become mantainer of the project

### ISSUE THREAD

**Issue by saccarosium** [alok/notational-fzf-vim#93]
I would love to mantaine this project. But I would ask if I can implement new features.

**Comment by rogeruiz** [comment]
I'd like to help too @saccarosium are you considering keeping it Vimscript and Python? I'd like to see some Neovim Lua compatibility. But even without Lua, I would like to help as well.

**Comment by saccarosium** [comment]
> I'd like to help too @saccarosium are you considering keeping it Vimscript and Python? I'd like to see some Neovim Lua compatibility. But even without Lua, I would still like to help as well.

I was planning to work add neovim lua comparability yes. And maybe get rid of the python dependencies all together.
